export const DRUGS = [
  {
    drugId: "m1",
    catId: ["c7"],
    drugName: "Klonidin",
    styrka: "15 µg/ml",
    recept: "1 ml catapressan 150 µg/ml + 9 ml NaCl",
    dosIµG: 1,
    obs: "barn > 1 år",
  },
  {
    drugId: "m2",
    catId: ["c8"],
    drugName: "Ondansetron",
    styrka: "2 mg/ml",
    dosiMg: 0.1,
    obs: "maximalt 2 ml",
  },
  {
    drugId: "m3",
    catId: ["c8"],
    drugName: "Betapred",
    styrka: "4 mg/ml",
    dosiMg: 0.2,
    obs: "maximalt 1 ml",
  },
  {
    drugId: "m4",
    catId: ["c8"],
    drugName: "Phenergan",
    styrka: "25 mg/ml",
    dosiMg: 0.5,
    obs: "maximalt 0,5 ml",
  },
  {
    drugId: "m5",
    catId: ["c1"],
    drugName: "Dexdor",
    styrka: "100 µg/ml",
    dosIµG: 1,
    dosIµG_2: 2,
    obs: "Nasalt. Späds inte! Anslag efter caa 20 min",
  },
  {
    drugId: "m6",
    catId: ["c2", "c5"],
    drugName: "Atropin",
    styrka: "0.5 mg/ml",
    dosIµG: 10,
    obs: "maximalt 1 ml",
  },
  {
    drugId: "m7",
    catId: ["c5"],
    drugName: "Atropin",
    styrka: "0.5 mg/ml",
    dosIµG: 20,
    obs: "Reversering",
  },

  {
    drugId: "m8",
    catId: ["c1"],
    drugName: "Midazolam",
    styrka: "1 mg/ml",
    dosiMg: 0.1,
  },
  {
    drugId: "m9",
    catId: ["c1"],
    drugName: "Midazolam",
    styrka: "5 mg/ml",
    dosiMg: 0.1,
  },
  {
    drugId: "m10",
    catId: ["c5"],
    drugName: "Robinul",
    styrka: "0.2 mg/ml",
    dosIµG: 10,
  },
  {
    drugId: "m11",
    catId: ["c2"],
    drugName: "Ketalar",
    styrka: "10 mg/ml",
    dosiMg: 2,
  },
  {
    drugId: "m12",
    catId: ["c2"],
    drugName: "Ketanest",
    styrka: "5 mg/ml",
    dosiMg: 0.5,
    dosiMg_2: 1,
  },
  {
    drugId: "m13",
    catId: ["c2"],
    drugName: "Ketanest",
    styrka: "25 mg/ml",
    dosiMg: 0.5,
    dosiMg_2: 1,
  },
  {
    drugId: "m14",
    catId: ["c2"],
    drugName: "Ketalar",
    styrka: "50 mg/ml",
    dosiMg: 2,
  },
  {
    drugId: "m15",
    catId: ["c2"],
    drugName: "Penthotal",
    styrka: "25 mg/ml",
    recept: "1 st Torrampull i 20 ml Sterilt vatten",
    dosiMg: 5,
  },
  {
    drugId: "m16",
    catId: ["c2"],
    drugName: "Propofol",
    styrka: "10 mg/ml",
    dosiMg: 2,
    dosiMg_2: 3,
  },
  {
    drugId: "m17",
    catId: ["c3"],
    drugName: "Alfentanil",
    styrka: "0.5 mg/ml",
    dosIµG: 5,
    dosIµG_2: 10,
    dosIµG_3: 20,
  },
  {
    drugId: "m18",
    catId: ["c1"],
    drugName: "Klonidin",
    styrka: "20 µg/ml",
    dosIµG: 5,
    obs: "Per os. 60 - 90 min i förväg",
  },
  {
    drugId: "m19",
    catId: ["c4"],
    drugName: "Celocurin",
    styrka: "50 mg/ml",
    dosiMg: 1,
  },
  {
    drugId: "m20",
    catId: ["c4"],
    drugName: "Atracurium",
    styrka: "10 mg/ml",
    dosiMg: 0.3,
    dosiMg_2: 0.5,
    obs: "för intubation",
  },
  {
    drugId: "m25",
    catId: ["c4"],
    drugName: "Pavulon",
    styrka: "2 mg/ml",
    dosiMg: 0.1,
    dosiMg_2: 0.02,
  },
  {
    drugId: "m21",
    catId: ["c6"],
    drugName: "Toradol",
    styrka: "30 mg/ml",
    dosiMg: 0.3,
    dosiMg_2: 0.5,
    obs: "för intubation",
  },
  {
    drugId: "m22",
    catId: ["c6"],
    drugName: "Paracetamol",
    styrka: "10 mg/ml",
    dosiMg: 7.5,
    dosiMg_2: 15,
    obs: "< 10 kg 7,5 mg/kg. Annars 15 mg/kg",
  },
];
